config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post 'cart/add'
  delete 'cart/remove'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkout.rb
class Checkout
  def initialize(pricing_rules)
    @items = []
    @pricing_rules = pricing_rules
  end

  def scan(item)
    # item = model Product
    @items << item
  end

  def total
    total = 0
    count_items.each do |item|
      code = item.keys.first.to_s # code of the product
      n_items = item.values.first # n items of this product
      product = Product.where(code: code).first
      discount = @pricing_rules.where(product: product).first # product.discounts.first
      total +=
        if discount.present?
          case discount.name
          when 'two for one'
            Discount.two_for_one(n_items, product)
          when 'strawberries'
            Discount.strawberries(n_items, product)
          end
        else
          Discount.only_sum(n_items, product)
        end
    end
    total
  end

  private

  def count_items
    counted = []
    @items.uniq.each do|item|
      n_items = @items.count(item)
      counted << { "#{item}": n_items }
    end
    counted
  end
end

app/models/discount.rb
class Discount < ApplicationRecord
  belongs_to :product, foreign_key: :product_id, primary_key: :code
  validates_uniqueness_of :name

  def self.two_for_one(n_items, product)
    price = product.price
    total =
      if n_items > 1
        n_items.even? ? price * n_items / 2 : ((price * (n_items - 1) / 2)) + price
      else
        price
      end
    total
  end

  def self.strawberries(n_items, product)
    price = product.price
    price = 4.5 if n_items >= 3
    price * n_items
  end

  def self.only_sum(n_items, product)
    price = product.price
    price * n_items
  end
end

app/models/product.rb
class Product < ApplicationRecord
  self.primary_key = :code
  has_many :discounts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_defaults

  def set_defaults
  session[:cart] = [] unless session[:cart].present?
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    item = request.params[:code]
    session[:cart] << item
    @cart = session[:cart].join(', ')
    @price = price_cart(session[:cart])
    respond_to do |format|
      format.js
    end
  end

  def remove
    session[:cart] = []
    redirect_to root_path
  end

  private

  def price_cart(cart)
    pricing_rules = Discount.all
    co = Checkout.new(pricing_rules)
    # much better: co = Checkout.new(Discount.all)
    cart.each do |item|
      co.scan(item)
    end
    price = co.total # is enough write co.total
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
    @cart = session[:cart].join(', ')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cart/add.js.erb
$('#cart').text('<%=@cart %>')
$('#price').text('<%=@price %>')

app/views/home/index.html.erb
<h1>Market</h1>
<h2>Cart: <span id="cart"><%= @cart %></span></h2>
<hr>
<h3>
  <%= link_to 'Delete Cart', cart_remove_path,
                            method: :delete, remote: true %>
</h3>
<hr>
<h2>Products</h2>
<% @products.each do |product| %>
  <%= form_with(url: cart_add_path, method: :post) do %>
    <%= hidden_field_tag(:code, product.code) %>
      <%= button_tag("add #{product.code} (£#{product.price}) " + product.name , class: '') %>
  <% end %>
<% end %>

<h2>To pay: £<span id="price">0</span></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kl</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>